import type { Routes } from "../type_flyweight/parse.ts";

import {
  ATTRIBUTE,
  ATTRIBUTE_DECLARATION,
  ATTRIBUTE_DECLARATION_CLOSE,
  ATTRIBUTE_SETTER,
  ATTRIBUTE_VALUE,
  CLOSE_NODE_CLOSED,
  CLOSE_NODE_SLASH,
  CLOSE_NODE_SPACE,
  CLOSE_TAGNAME,
  ERROR,
  INDEPENDENT_NODE,
  INDEPENDENT_NODE_CLOSED,
  NODE,
  NODE_CLOSED,
  NODE_SPACE,
  TAGNAME,
  TEXT,
} from "../type_flyweight/constants.ts";

const routes: Routes = {
  INITIAL: {
    "<": NODE,
    DEFAULT: TEXT,
  },
  // TEXT
  TEXT: {
    "<": NODE,
    DEFAULT: TEXT,
  },
  // NODE
  NODE: {
    " ": ERROR,
    "\n": NODE,
    "\t": NODE,
    "/": CLOSE_NODE_SLASH,
    ">": ERROR,
    DEFAULT: TAGNAME,
  },
  CLOSE_NODE_SLASH: {
    " ": ERROR,
    DEFAULT: CLOSE_TAGNAME,
  },
  TAGNAME: {
    ">": NODE_CLOSED,
    " ": NODE_SPACE,
    "\n": NODE_SPACE,
    "\t": NODE_SPACE,
    "/": INDEPENDENT_NODE,
    DEFAULT: TAGNAME,
  },
  CLOSE_TAGNAME: {
    ">": CLOSE_NODE_CLOSED,
    " ": CLOSE_NODE_SPACE,
    "\n": CLOSE_NODE_SPACE,
    "\t": CLOSE_NODE_SPACE,
    DEFAULT: CLOSE_TAGNAME,
  },
  // close node space
  CLOSE_NODE_SPACE: {
    ">": CLOSE_NODE_CLOSED,
    DEFAULT: CLOSE_NODE_SPACE,
  },
  INDEPENDENT_NODE: {
    ">": INDEPENDENT_NODE_CLOSED,
    DEFAULT: INDEPENDENT_NODE,
  },
  NODE_CLOSED: {
    "<": NODE,
    DEFAULT: TEXT,
  },
  CLOSE_NODE_CLOSED: {
    "<": NODE,
    DEFAULT: TEXT,
  },
  INDEPENDENT_NODE_CLOSED: {
    "<": NODE,
    DEFAULT: TEXT,
  },
  // ATTRIBUTE
  NODE_SPACE: {
    ">": NODE_CLOSED,
    " ": NODE_SPACE,
    "\n": NODE_SPACE,
    "\t": NODE_SPACE,
    "/": INDEPENDENT_NODE,
    DEFAULT: ATTRIBUTE,
  },
  ATTRIBUTE: {
    " ": NODE_SPACE,
    "\n": NODE_SPACE,
    "\t": NODE_SPACE,
    "=": ATTRIBUTE_SETTER,
    ">": NODE_CLOSED,
    "/": INDEPENDENT_NODE,
    DEFAULT: ATTRIBUTE,
  },
  ATTRIBUTE_SETTER: {
    '"': ATTRIBUTE_DECLARATION,
    "\n": NODE_SPACE,
    DEFAULT: NODE_SPACE,
  },
  ATTRIBUTE_DECLARATION: {
    '"': ATTRIBUTE_DECLARATION_CLOSE,
    DEFAULT: ATTRIBUTE_VALUE,
  },
  ATTRIBUTE_VALUE: {
    '"': ATTRIBUTE_DECLARATION_CLOSE,
    DEFAULT: ATTRIBUTE_VALUE,
  },
  ATTRIBUTE_DECLARATION_CLOSE: {
    ">": INDEPENDENT_NODE_CLOSED,
    "/": INDEPENDENT_NODE,
    DEFAULT: NODE_SPACE,
  },
};

export { routes };
